name: CMake Build & Test

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

    - name: Build Code
      run: cmake --build ${{github.workspace}}/build

    - name: Run Tests
      working-directory: ${{github.workspace}}/build
      run: ctest --output-on-failure -C Release
